from collections import defaultdict
from typing import Iterable

from .strategy_context import StrategyContext
from .strategy_interface import Strategy
from .strategy_output import StrategyOutput
from .strategy_requirements import StrategyRequirements
from market_data.models import Tick

class StrategyDispatcher:
    """
    Routes prepared market-data inputs to eligible strategy instances.

    The dispatcher is responsible for:
        - finding eligible strategies
        - invoking strategies
        - collecting strategy outputs

    The dispatcher does not:
        - create strategies
        - contain strategy business logic
        - manage users
        - perform risk checks
        - execute orders
        - publish events
    """

    def __init__(
        self,
        strategies: Iterable[Strategy] = (),
    ) -> None:
        self._strategies: list[Strategy] = list(strategies)

        self._context_routes: dict[
            tuple[str, str],
            list[Strategy],
        ] = defaultdict(list)

        self._tick_routes: dict[
            str,
            list[Strategy],
        ] = defaultdict(list)

        self._build_routes()


    def set_strategies(
        self,
        strategies: Iterable[Strategy],
    ) -> None:
        """
        Replace the currently registered strategies and rebuild
        the routing indexes.
        """
        self._strategies = list(strategies)

        self._build_routes()

        
    def _build_routes(self) -> None:
        """
        Build routing indexes from strategy requirements.
        """
        self._context_routes.clear()
        self._tick_routes.clear()

        for strategy in self._strategies:
            requirements = strategy.get_requirements()

            self._register_context_routes(
                strategy,
                requirements,
            )

            if requirements.requires_ticks:
                self._tick_routes[
                    strategy.symbol
                ].append(strategy)

    def _register_context_routes(
        self,
        strategy: Strategy,
        requirements: StrategyRequirements,
    ) -> None:
        """
        Register a strategy for every candle timeframe it requires.
        """
        for timeframe in requirements.candle_timeframes:
            self._context_routes[
                (strategy.symbol, timeframe)
            ].append(strategy)

    def dispatch_context(
        self,
        context: StrategyContext,
    ) -> list[StrategyOutput]:
        """
        Dispatch a completed context to eligible strategies.

        Returns every signal/output generated by those strategies.
        """
        outputs: list[StrategyOutput] = []

        strategies = self._context_routes.get(
            (context.symbol, context.timeframe),
            [],
        )

        for strategy in strategies:
            output = strategy.on_context(context)

            if output is not None:
                outputs.append(output)

        return outputs

    def dispatch_tick(
        self,
        tick: Tick,
    ) -> list[StrategyOutput]:
        """
        Dispatch a tick to strategies that require tick data.

        A StrategyContext is created for each eligible strategy because
        the strategy's timeframe is part of its configuration.
        """
        outputs: list[StrategyOutput] = []

        strategies = self._tick_routes.get(
            tick.symbol,
            [],
        )

        print(
            f"StrategyDispatcher: tick={tick.symbol}, "
            f"eligible_strategies={len(strategies)}"
        )

        for strategy in strategies:
            context = StrategyContext(
                symbol=strategy.symbol,
                timeframe=strategy.timeframe,
                start_time=tick.timestamp,
                end_time=tick.timestamp,
                tick=tick,
            )

            output = strategy.on_tick(context)

            if output is not None:
                outputs.append(output)

        return outputs


