from dataclasses import dataclass
from datetime import datetime
from enum import Enum

from strategy.strategy_models import StrategyGroup


class SignalType(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"


class SignalSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


@dataclass(frozen=True)
class StrategyOutput:
    """
    Represents the output generated by a strategy.

    This is a strategy decision only.
    """

    strategy_group: StrategyGroup
    signal_type: SignalType
    side: SignalSide
    timestamp: datetime