from enum import Enum


class EventType(Enum):

    # MARKET SESSION EVENTS
    MARKET_OPEN = "MARKET_OPEN"
    MARKET_CLOSE = "MARKET_CLOSE"


    # TICKS AND CANDLE CLOSED EVENTS
    TICK_RECEIVED = "TICK_RECEIVED"
    CANDLE_BATCH_CLOSED = "CANDLE_BATCH_CLOSED"

    # SESSION EVENTS
    SESSIONS_READY = "SESSIONS_READY"

