from enum import Enum


class EventType(Enum):

    # MARKET SESSION EVENTS
    MARKET_OPEN = "MARKET_OPEN"
    MARKET_CLOSE = "MARKET_CLOSE"

    # SESSION EVENTS
    SESSIONS_READY = "SESSIONS_READY"


    # TICKS AND CANDLE CLOSED EVENTS
    TICK_RECEIVED = "TICK_RECEIVED"
    CANDLE_BATCH_CLOSED = "CANDLE_BATCH_CLOSED"

    # INDICATOR EVENTS
    INDICATOR_BATCH_UPDATED = "INDICATOR_BATCH_UPDATED"

    # STRATEGY EVENTS
    STRATEGY_SIGNAL_GENERATED = "STRATEGY_SIGNAL_GENERATED"
    
